import React, { useState } from "react";

export function ItemRow({ item, onUpdate, onRemove }) {
  const [editing, setEditing] = useState(false);
  const isAuto = item.fromMenu && !editing;
  return (
    <tr className="border-b border-carbon-08 print:border-b print:border-[#E6E1DC] group hover:bg-black/5 transition-colors">
      <td className="py-2 px-3 align-middle print:py-1 print:px-1">
        <div className="text-[13px] font-bold text-carbon-300 print:text-[#1A1714] print:text-xs">{item.name}</div>
        {item.fromMenu && !editing && <div className="text-[9px] font-bold text-[#F59E0B] uppercase tracking-widest mt-0.5 print:hidden">from menu</div>}
        {item.variation && <div className="text-[10px] italic font-semibold text-carbon-50 mt-0.5 bg-black/5 px-1.5 py-0.5 rounded-sm inline-block print:bg-transparent print:p-0 print:text-[#54453A]">{item.variation}</div>}
      </td>
      <td className="py-2 px-3 align-middle print:py-1 print:px-1"><input className={`w-14 text-center font-extrabold text-[13px] bg-transparent border rounded-lg p-1.5 transition-colors focus:outline-none print:w-full print:text-center print:text-xs print:border-none print:p-0 print:bg-transparent print:text-[#1A1714] ${isAuto ? "text-[#D97706] bg-[#FEF3C7] border-[#FCD34D] hover:bg-[#FDE68A]" : "text-carbon-300 border-transparent hover:border-bd hover:bg-black/5 focus:border-accent focus:bg-white"}`} type="number" placeholder="—" value={item.quantity || ""} onFocus={() => setEditing(true)} onBlur={() => setEditing(false)} onChange={e => onUpdate({ quantity: e.target.value })} /></td>
      <td className="py-2 px-3 align-middle print:py-1 print:px-1"><input className="w-12 text-center text-[11px] font-bold text-carbon-50 bg-transparent border border-transparent rounded-lg p-1.5 hover:border-bd hover:bg-black/5 focus:border-accent focus:bg-white focus:outline-none print:w-full print:text-center print:border-none print:p-0 print:bg-transparent print:text-[#54453A] print:font-normal" value={item.unit || ""} onChange={e => onUpdate({ unit: e.target.value })} /></td>
      <td className="py-2 px-3 align-middle print:py-1 print:px-1"><input className="w-full bg-transparent border border-transparent rounded-lg p-1.5 text-xs font-semibold text-carbon-300 hover:border-bd hover:bg-black/5 focus:border-accent focus:bg-white focus:outline-none print:border-none print:p-0 print:bg-transparent print:text-[#1A1714] print:font-bold" value={item.container || ""} onChange={e => onUpdate({ container: e.target.value })} /></td>
      <td className="py-2 px-3 align-middle print:py-1 print:px-1"><input className="w-full bg-transparent border border-transparent rounded-lg p-1.5 text-xs font-semibold text-carbon-300 hover:border-bd hover:bg-black/5 focus:border-accent focus:bg-white focus:outline-none print:border-none print:p-0 print:bg-transparent print:text-[#1A1714] print:font-bold" placeholder="notes or variation…" value={item.notes || ""} style={{ fontStyle: item.notes ? "italic" : "normal" }} onChange={e => onUpdate({ notes: e.target.value })} /></td>
      <td className="py-2 px-3 align-middle print:py-1 print:px-1"><input className={`w-16 text-center font-bold rounded-lg p-1.5 transition-colors focus:outline-none print:w-full print:bg-transparent print:rounded-none ${item.prepped?.trim() ? "bg-[#D1FAE5] text-[#047857] border border-[#A7F3D0] print:text-[#1A1714] print:border-b print:border-[#1A1714] print:italic" : "bg-transparent text-carbon-300 border border-transparent hover:border-bd hover:bg-black/5 focus:border-accent focus:bg-white print:border-none print:border-b print:border-[#E6E1DC]"}`} placeholder="initials" value={item.prepped || ""} onChange={e => onUpdate({ prepped: e.target.value })} /></td>
      <td className="py-2 px-3 align-middle print:py-1 print:px-1"><input className="w-16 text-center font-bold bg-transparent text-carbon-300 border border-transparent rounded-lg p-1.5 hover:border-bd hover:bg-black/5 focus:border-accent focus:bg-white focus:outline-none print:w-full print:p-0 print:bg-transparent print:text-[#1A1714] print:border-none print:border-b print:border-[#E6E1DC] print:rounded-none" placeholder="qty" value={item.loaded || ""} onChange={e => onUpdate({ loaded: e.target.value })} /></td>
      <td className="py-2 px-3 align-middle print:py-1 print:px-1"><input className="w-16 text-center font-bold bg-transparent text-carbon-300 border border-transparent rounded-lg p-1.5 hover:border-bd hover:bg-black/5 focus:border-accent focus:bg-white focus:outline-none print:w-full print:p-0 print:bg-transparent print:text-[#1A1714] print:border-none print:border-b print:border-[#E6E1DC] print:rounded-none" placeholder="qty" value={item.returned || ""} onChange={e => onUpdate({ returned: e.target.value })} /></td>
      <td className="py-2 px-3 align-middle print:py-1 print:px-1"><button className="w-6 h-6 rounded-full bg-transparent border-none text-muted text-lg font-bold cursor-pointer hover:bg-red hover:text-white transition-colors flex items-center justify-center leading-none opacity-0 group-hover:opacity-100 print:hidden" onClick={onRemove}>×</button></td>
    </tr>
  );
}
